# Generated by Django 5.0.3 on 2024-03-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_student_scheme_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='scheme',
            field=models.FloatField(),
        ),
    ]
