# Generated by Django 4.2 on 2024-04-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_scheme_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='access_to_web',
            field=models.BooleanField(default=False),
        ),
    ]
