# Generated by Django 5.0.4 on 2024-04-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='other_fee',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
