# Generated by Django 5.0.4 on 2024-04-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_student_other_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='certificate_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='course_completed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='examination_date',
            field=models.DateField(null=True),
        ),
    ]
