# Generated by Django 5.0.4 on 2024-04-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_student_certificate_issued_student_course_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='other_fee',
            field=models.IntegerField(null=True),
        ),
    ]
