# Generated by Django 5.0.4 on 2024-04-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_alter_student_other_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_completed',
            field=models.BooleanField(default=False),
        ),
    ]
