# Generated by Django 5.0.4 on 2024-05-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_enquiry_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='address2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='address3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='contact_no1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='contact_no2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
