# Generated by Django 5.0.4 on 2024-05-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_branch_address1_branch_address2_branch_address3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='gmap',
            field=models.URLField(blank=True, null=True),
        ),
    ]
