# Generated by Django 5.0.4 on 2024-05-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_branch_gmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='gmap',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
