# Generated by Django 5.0.4 on 2024-06-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_alter_branch_gmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_admission_fee',
            field=models.BooleanField(default=False),
        ),
    ]
