# Generated by Django 5.0.4 on 2024-08-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_payment_is_admission_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='education',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
