# Generated by Django 5.0.3 on 2024-03-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_testimonal_home_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='bgimage',
            field=models.ImageField(default=1, upload_to='Background'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='subtitle',
            field=models.CharField(default='Skill Board Education', max_length=50),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(default='Learning Today, Leading Tomorrow', max_length=50),
        ),
    ]
