# Generated by Django 5.0.3 on 2024-03-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_home_bgimage_alter_home_subtitle_alter_home_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bgimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgimage', models.ImageField(upload_to='Background')),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='bgimage',
        ),
    ]
