# Generated by Django 5.0.4 on 2024-04-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_rename_title_home_qoute1_rename_subtitle_home_qoute2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='about',
            field=models.TextField(default='skillboard education pandikkad', null=True),
        ),
    ]
