# Generated by Django 5.0.4 on 2024-04-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_alter_home_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(default='skillboard education pandikkad', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='about',
        ),
    ]
