# Generated by Django 5.0.4 on 2024-05-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_about_remove_home_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='mission',
            field=models.TextField(default='skillboard education pandikkad', null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='vision',
            field=models.TextField(default='skillboard education pandikkad', null=True),
        ),
    ]
