# Generated by Django 5.0.4 on 2024-05-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_about_mission_about_vision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='qoute1',
            field=models.CharField(default='Learning Today, Leading Tomorrow', max_length=80),
        ),
        migrations.AlterField(
            model_name='home',
            name='qoute2',
            field=models.CharField(default='Skill Board Education', max_length=80),
        ),
    ]
