# Generated by Django 5.0.4 on 2024-05-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_alter_home_qoute1_alter_home_qoute2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos')),
            ],
        ),
    ]
