# Generated by Django 5.0.4 on 2024-05-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_afflogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgGallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ImageGallary')),
            ],
        ),
    ]
